#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"
EXPECTED_FLUTTER="$(python3 - <<'PY'
import json
from pathlib import Path
print(json.loads(Path('.fvmrc').read_text())['flutter'])
PY
)"

fail() { printf 'BOOTSTRAP BLOCKED: %s\n' "$*" >&2; exit 2; }
step() { printf '\n==> %s\n' "$*"; }

if command -v flutter >/dev/null 2>&1; then
  step "Existing Flutter SDK"
  flutter --version
else
  step "Flutter ${EXPECTED_FLUTTER} bootstrap"
  command -v git >/dev/null 2>&1 || fail "git is required to install the pinned Flutter SDK."
  command -v curl >/dev/null 2>&1 || fail "curl is required to install the pinned Flutter SDK."

  SDK_ROOT="${SNIPER_TURK_FLUTTER_HOME:-$HOME/.sniper-turk/flutter}"
  # Never let a mistyped custom SDK path turn the bootstrap fallback into a
  # destructive directory remover.  Existing targets must be a real Flutter
  # git checkout before any update/replacement path is allowed to delete them.
  [[ ! -L "$SDK_ROOT" ]] || fail "Flutter SDK destination must not be a symlink: $SDK_ROOT"
  mkdir -p "$(dirname "$SDK_ROOT")"
  if [[ -e "$SDK_ROOT" && ! -d "$SDK_ROOT/.git" ]]; then
    fail "Flutter SDK destination already exists and is not a git checkout: $SDK_ROOT"
  fi
  if [[ -d "$SDK_ROOT/.git" ]]; then
    ORIGIN_URL="$(git -C "$SDK_ROOT" remote get-url origin 2>/dev/null || true)"
    [[ "$ORIGIN_URL" == "https://github.com/flutter/flutter.git" ]] \
      || fail "Existing SDK destination is not the official Flutter checkout: $SDK_ROOT"
  fi
  if [[ ! -d "$SDK_ROOT/.git" ]]; then
    if ! git clone --filter=blob:none https://github.com/flutter/flutter.git "$SDK_ROOT"; then
      printf 'GitHub Flutter clone failed; trying the official Google Flutter SDK archive.\n' >&2
      rm -rf "$SDK_ROOT"
      python3 tools/install_pinned_flutter.py --version "$EXPECTED_FLUTTER" --destination "$SDK_ROOT" \
        || fail "Both GitHub and the official Flutter SDK archive bootstrap failed."
    fi
  fi
  if [[ -d "$SDK_ROOT/.git" ]]; then
    if ! git -C "$SDK_ROOT" fetch --tags origin || ! git -C "$SDK_ROOT" checkout --detach "$EXPECTED_FLUTTER"; then
      printf 'GitHub Flutter update failed; trying the official Google Flutter SDK archive transactionally.\n' >&2
      # Preserve a pre-existing, verified official checkout until the fallback
      # archive is fully installed. A network/archive failure must not destroy
      # the developer's previously usable SDK tree.
      SDK_BACKUP="${SDK_ROOT}.sniper-turk-backup.$$"
      [[ ! -e "$SDK_BACKUP" && ! -L "$SDK_BACKUP" ]] \
        || fail "Refusing to overwrite Flutter SDK rollback path: $SDK_BACKUP"
      mv -- "$SDK_ROOT" "$SDK_BACKUP"
      if python3 tools/install_pinned_flutter.py --version "$EXPECTED_FLUTTER" --destination "$SDK_ROOT"; then
        rm -rf -- "$SDK_BACKUP"
      else
        rm -rf -- "$SDK_ROOT"
        mv -- "$SDK_BACKUP" "$SDK_ROOT"
        fail "Both GitHub and the official Flutter SDK archive bootstrap failed; previous SDK restored."
      fi
    fi
  fi
  export PATH="$SDK_ROOT/bin:$PATH"
fi

command -v flutter >/dev/null 2>&1 || fail "Flutter installation completed without a usable flutter executable."
ACTUAL="$(flutter --version --machine 2>/dev/null | python3 -c 'import json,sys; print(json.load(sys.stdin)["frameworkVersion"])' 2>/dev/null || true)"
[[ "$ACTUAL" == "$EXPECTED_FLUTTER" ]] || fail "Expected Flutter ${EXPECTED_FLUTTER}, found ${ACTUAL:-unknown}."

if [[ ! -s pubspec.lock ]]; then
  step "First resolver lockfile bootstrap"
  SNIPER_TURK_BOOTSTRAP_LOCKFILE=1 tools/claude_flutter_verify.sh
  printf '\nBOOTSTRAP VERIFY PASS: pubspec.lock was generated by Flutter %s and the verification chain passed.\n' "$EXPECTED_FLUTTER"
  printf 'Review and commit pubspec.lock, then rerun tools/claude_flutter_verify.sh without bootstrap mode.\n'
else
  exec tools/claude_flutter_verify.sh
fi
