#!/usr/bin/env python3
"""Install the Sniper Türk app icon and launch screen into the iOS scaffold.

The scaffold is regenerated by `flutter create` in CI, so the branding is
applied here from committed source files in branding/ios/:

* AppIcon-1024.png      -> Assets.xcassets/AppIcon.appiconset (single-size
                           1024 icon; Xcode derives every other size)
* LaunchImage{,@2x,@3x}.png -> Assets.xcassets/LaunchImage.imageset
* LaunchScreen.storyboard background -> the logo's dark background colour

Fails closed when a source file is missing, the icon has an alpha channel
(App Store rejects it) or the storyboard has an unexpected shape.
Idempotent.
"""
from __future__ import annotations

import json
import re
import shutil
import struct
import sys
from pathlib import Path

ICON = "AppIcon-1024.png"
LAUNCH = ("LaunchImage.png", "LaunchImage@2x.png", "LaunchImage@3x.png")
# #090909, the colour the launch logo fades into.
BG = 'red="0.035" green="0.035" blue="0.035" alpha="1"'
BG_TAG = (
    f'<color key="backgroundColor" {BG} colorSpace="custom" '
    'customColorSpace="sRGB"/>'
)


def png_info(path: Path) -> tuple[int, int, int]:
    """(width, height, colour type) from the PNG IHDR chunk."""
    data = path.read_bytes()[:33]
    if data[:8] != b"\x89PNG\r\n\x1a\n" or data[12:16] != b"IHDR":
        raise ValueError(f"{path.name} is not a PNG")
    width, height = struct.unpack(">II", data[16:24])
    return width, height, data[25]


def check_sources(branding: Path) -> None:
    for name in (ICON, *LAUNCH):
        if not (branding / name).is_file():
            raise ValueError(f"missing branding file: {name}")
    w, h, colour = png_info(branding / ICON)
    if (w, h) != (1024, 1024):
        raise ValueError(f"{ICON} must be 1024x1024, got {w}x{h}")
    if colour not in (0, 2):  # greyscale or RGB, no alpha
        raise ValueError(f"{ICON} must not have an alpha channel")


def patch_storyboard(text: str) -> str:
    if BG_TAG in text:
        return text
    pattern = r'<color key="backgroundColor"[^>]*/>'
    if not re.search(pattern, text):
        raise ValueError("LaunchScreen.storyboard has no backgroundColor")
    return re.sub(pattern, BG_TAG, text, count=1)


def install(branding: Path, runner: Path) -> None:
    check_sources(branding)
    assets = runner / "Assets.xcassets"
    storyboard = runner / "Base.lproj" / "LaunchScreen.storyboard"
    if not storyboard.is_file():
        raise ValueError(f"missing {storyboard}")

    icon_set = assets / "AppIcon.appiconset"
    if icon_set.exists():
        shutil.rmtree(icon_set)
    icon_set.mkdir(parents=True)
    shutil.copyfile(branding / ICON, icon_set / ICON)
    (icon_set / "Contents.json").write_text(
        json.dumps(
            {
                "images": [
                    {
                        "filename": ICON,
                        "idiom": "universal",
                        "platform": "ios",
                        "size": "1024x1024",
                    }
                ],
                "info": {"author": "xcode", "version": 1},
            },
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    launch_set = assets / "LaunchImage.imageset"
    if launch_set.exists():
        shutil.rmtree(launch_set)
    launch_set.mkdir(parents=True)
    images = []
    for name, scale in zip(LAUNCH, ("1x", "2x", "3x")):
        shutil.copyfile(branding / name, launch_set / name)
        images.append({"filename": name, "idiom": "universal", "scale": scale})
    (launch_set / "Contents.json").write_text(
        json.dumps({"images": images, "info": {"author": "xcode", "version": 1}}, indent=2)
        + "\n",
        encoding="utf-8",
    )

    storyboard.write_text(
        patch_storyboard(storyboard.read_text(encoding="utf-8")), encoding="utf-8"
    )


def main(argv: list[str]) -> int:
    if len(argv) != 3:
        print("usage: configure_ios_branding.py BRANDING_DIR RUNNER_DIR", file=sys.stderr)
        return 2
    try:
        install(Path(argv[1]), Path(argv[2]))
    except ValueError as e:
        print(f"cannot apply iOS branding: {e}", file=sys.stderr)
        return 1
    print("iOS app icon and launch screen installed")
    return 0


if __name__ == "__main__":
    raise SystemExit(main(sys.argv))
