#!/usr/bin/env python3
"""Offline cross-check of the experimental G1/G7 solver equations.

NOT an acceptance run. The production gate stays closed until
validation/py_ballisticcalc_vectors.json is generated by the pinned external
py-ballisticcalc==2.2.10 and compared by tools/compare_reference_vectors.dart.
This script cannot replace that, because:

  * it is written by the same project, so it is not an independent reference;
  * it re-implements lib/core/aerodynamic_trajectory_solver.dart in Python, it
    does not execute the Dart code.

What it does catch without network/Flutter access: unit-conversion mistakes,
drag-law errors, zero-angle logic errors and integration-step error. It reads the
G1/G7 tables from lib/core/standard_drag_tables.dart so the data is not
duplicated, and checks:

  1. analytic limit: constant Cd, no gravity -> v(x) = v0 * exp(-k x);
  2. a port of the Dart fixed-step RK4 + bisection zero against a different
     integrator (SciPy DOP853, tight tolerances) on the four predeclared cases;
  3. step-size convergence of the Dart-style integrator.

Exit code is non-zero when a check fails. A pass here is evidence about the
equations only.
"""
from __future__ import annotations

import json
import math
import re
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
TABLES = ROOT / "lib/core/standard_drag_tables.dart"
ACCEPTANCE = ROOT / "validation/acceptance.json"

G = 9.80665
LB_IN2_TO_KG_M2 = 703.0695796391593
GAMMA = 1.4
RD, RV = 287.05, 461.495
GRAIN_KG = 0.00006479891

ATMOSPHERES = {
    "icao": dict(t_c=15.0, p_hpa=1013.25, rh=0.0),
    "hot_high": dict(t_c=30.0, p_hpa=1013.25, rh=0.0),
}
CASES = [
    dict(id="g1_pcp_baseline", model="g1", bc=0.12, mv=270.0, zero=25.0, sight_mm=60.0, atm="icao"),
    dict(id="g7_rifle_baseline", model="g7", bc=0.243, mv=800.0, zero=100.0, sight_mm=45.0, atm="icao"),
    dict(id="g1_pcp_hot_high", model="g1", bc=0.12, mv=270.0, zero=25.0, sight_mm=60.0, atm="hot_high"),
    dict(id="g7_rifle_hot_high", model="g7", bc=0.243, mv=800.0, zero=100.0, sight_mm=45.0, atm="hot_high"),
]
# Mirrors tools/generate_reference_vectors.py (v348): G7 is sampled out to 1500 m
# so the transonic/subsonic part of the flight is exercised, not only the muzzle region.
RANGES_BY_MODEL = {
    "g1": [25.0, 50.0, 100.0, 200.0, 300.0],
    "g7": [100.0, 300.0, 600.0, 1000.0, 1500.0],
}


def load_tables() -> dict[str, list[tuple[float, float]]]:
    text = TABLES.read_text(encoding="utf-8")
    out = {}
    for name in ("g1", "g7"):
        block = re.search(rf"static final {name} = DragTable\(const \[(.*?)\]\);", text, re.S)
        if not block:
            raise SystemExit(f"cannot find {name} table in {TABLES}")
        pts = [(float(m), float(c)) for m, c in re.findall(r"DragSample\(([\d.]+),([\d.]+)\)", block.group(1))]
        if len(pts) < 2 or any(b[0] <= a[0] for a, b in zip(pts, pts[1:])):
            raise SystemExit(f"{name} table is not strictly increasing")
        out[name] = pts
    return out


def cd_at(table: list[tuple[float, float]], mach: float) -> float:
    if mach <= table[0][0]:
        return table[0][1]
    if mach >= table[-1][0]:
        return table[-1][1]
    lo, hi = 0, len(table) - 1
    while hi - lo > 1:
        mid = (lo + hi) // 2
        if table[mid][0] <= mach:
            lo = mid
        else:
            hi = mid
    (m0, c0), (m1, c1) = table[lo], table[hi]
    return c0 + (c1 - c0) * (mach - m0) / (m1 - m0)


class Air:
    def __init__(self, t_c: float, p_hpa: float, rh: float):
        tk = t_c + 273.15
        pv = 6.112 * math.exp(17.62 * t_c / (243.12 + t_c)) * 100 * rh / 100
        pt = p_hpa * 100
        self.rho = (pt - pv) / (RD * tk) + pv / (RV * tk)
        self.sound = math.sqrt(GAMMA * pt / self.rho)


def make_accel(table, bc, air: Air, const_cd: float | None = None, gravity: float = G):
    bc_si = bc * LB_IN2_TO_KG_M2

    def f(_t, s):
        x, y, z, vx, vy, vz = s
        v = math.sqrt(vx * vx + vy * vy + vz * vz)
        cd = const_cd if const_cd is not None else cd_at(table, v / air.sound)
        decel = 0.5 * air.rho * cd * (math.pi / 4) * v * v / bc_si
        k = -decel / v if v else 0.0
        return [vx, vy, vz, k * vx, k * vy - gravity, k * vz]

    return f


def rk4_step(f, s, dt):
    k1 = f(0, s)
    k2 = f(0, [a + b * dt / 2 for a, b in zip(s, k1)])
    k3 = f(0, [a + b * dt / 2 for a, b in zip(s, k2)])
    k4 = f(0, [a + b * dt for a, b in zip(s, k3)])
    return [a + dt / 6 * (p + 2 * q + 2 * r + w) for a, p, q, r, w in zip(s, k1, k2, k3, k4)]


def launch(mv, angle, sight_m):
    return [0.0, -sight_m, 0.0, mv * math.cos(angle), mv * math.sin(angle), 0.0]


def height_at(f, mv, angle, sight_m, rng, dt):
    s, t = launch(mv, angle, sight_m), 0.0
    for _ in range(4_000_000):
        p = s
        s = rk4_step(f, s, dt)
        t += dt
        if s[0] >= rng:
            fr = (rng - p[0]) / (s[0] - p[0])
            return p[1] + (s[1] - p[1]) * fr
        if s[3] <= 0:
            break
    raise RuntimeError("did not reach zero range")


def zero_angle(f, mv, sight_m, zero, dt):
    lo, hi = -0.05, 0.25
    ylo, yhi = height_at(f, mv, lo, sight_m, zero, dt), height_at(f, mv, hi, sight_m, zero, dt)
    if math.copysign(1, ylo) == math.copysign(1, yhi):
        raise RuntimeError("cannot bracket zero")
    for _ in range(60):
        mid = (lo + hi) / 2
        ym = height_at(f, mv, mid, sight_m, zero, dt)
        if abs(ym) < 1e-8:
            return mid
        if math.copysign(1, ym) == math.copysign(1, ylo):
            lo, ylo = mid, ym
        else:
            hi = mid
    return (lo + hi) / 2


def dart_style(f, mv, sight_m, zero, ranges, dt):
    """Port of AerodynamicTrajectorySolver.solve for a no-wind case."""
    angle = zero_angle(f, mv, sight_m, zero, dt)
    s, t, i, out = launch(mv, angle, sight_m), 0.0, 0, []
    while i < len(ranges):
        p, pt = s, t
        s = rk4_step(f, s, dt)
        t += dt
        while i < len(ranges) and s[0] >= ranges[i]:
            fr = (ranges[i] - p[0]) / (s[0] - p[0])
            lerp = lambda a, b: a + (b - a) * fr
            out.append(dict(drop=-lerp(p[1], s[1]),
                            v=math.sqrt(sum(lerp(p[k], s[k]) ** 2 for k in (3, 4, 5))),
                            t=lerp(pt, t)))
            i += 1
    return angle, out


def reference_style(f, mv, sight_m, zero, ranges, angle):
    """Independent integration: DOP853 with tight tolerances and exact x events."""
    from scipy.integrate import solve_ivp

    # Same mechanical angle as the solver under test is NOT assumed: re-solve the
    # zero with the independent integrator using brentq.
    from scipy.optimize import brentq

    def run(a, stop_x):
        ev = lambda _t, s: s[0] - stop_x
        ev.terminal, ev.direction = True, 1
        r = solve_ivp(f, (0, 60), launch(mv, a, sight_m), method="DOP853", rtol=1e-12, atol=1e-12, events=ev, dense_output=False)
        return r.y_events[0][0], r.t_events[0][0]

    ang = brentq(lambda a: run(a, zero)[0][1], -0.05, 0.25, xtol=1e-14)
    out = []
    for rng in ranges:
        st, tt = run(ang, rng)
        out.append(dict(drop=-st[1], v=math.sqrt(st[3] ** 2 + st[4] ** 2 + st[5] ** 2), t=tt))
    return ang, out


def check_analytic() -> list[str]:
    errs = []
    cd, bc, v0 = 0.3, 0.2, 300.0
    air = Air(15.0, 1013.25, 0.0)
    f = make_accel(None, bc, air, const_cd=cd, gravity=0.0)
    k = air.rho * cd * math.pi / (8 * bc * LB_IN2_TO_KG_M2)
    s, dt = [0.0, 0.0, 0.0, v0, 0.0, 0.0], 0.0005
    for xt in (50.0, 100.0, 200.0):
        while s[0] < xt:
            p = s
            s = rk4_step(f, s, dt)
        fr = (xt - p[0]) / (s[0] - p[0])
        v = p[3] + (s[3] - p[3]) * fr
        want = v0 * math.exp(-k * xt)
        if abs(v - want) > 1e-3:
            errs.append(f"analytic decay mismatch at {xt} m: {v:.6f} vs {want:.6f}")
    return errs


def main() -> int:
    tol = json.loads(ACCEPTANCE.read_text(encoding="utf-8"))["tolerances"]
    tables = load_tables()
    errors = check_analytic()
    print("analytic constant-Cd decay:", "FAIL" if errors else "ok")
    worst = dict(h=0.0, v=0.0, t=0.0)
    for c in CASES:
        a = ATMOSPHERES[c["atm"]]
        air = Air(a["t_c"], a["p_hpa"], a["rh"])
        f = make_accel(tables[c["model"]], c["bc"], air)
        sight = c["sight_mm"] / 1000
        ranges = RANGES_BY_MODEL[c["model"]]
        ang_d, dart = dart_style(f, c["mv"], sight, c["zero"], ranges, 0.0005)
        ang_r, ref = reference_style(f, c["mv"], sight, c["zero"], ranges, None)
        dh = max(abs(d["drop"] - r["drop"]) for d, r in zip(dart, ref))
        dv = max(abs(d["v"] - r["v"]) for d, r in zip(dart, ref))
        dt_ = max(abs(d["t"] - r["t"]) for d, r in zip(dart, ref))
        worst["h"], worst["v"], worst["t"] = max(worst["h"], dh), max(worst["v"], dv), max(worst["t"], dt_)
        # step-size convergence of the Dart-style integrator
        _, coarse = dart_style(f, c["mv"], sight, c["zero"], ranges, 0.002)
        conv = max(abs(d["drop"] - r["drop"]) for d, r in zip(dart, coarse))
        print(f"{c['id']:20s} zero={ang_d*1000:8.4f} mrad (ref {ang_r*1000:8.4f}) "
              f"dh={dh:.2e} m dv={dv:.2e} m/s dt={dt_:.2e} s step-conv={conv:.2e} m")
        if dh > tol["height_m_absolute"] or dv > tol["velocity_mps_absolute"] or dt_ > tol["time_s_absolute"]:
            errors.append(f"{c['id']}: exceeds acceptance tolerances")
        if conv > tol["height_m_absolute"] / 4:
            errors.append(f"{c['id']}: integration step not converged ({conv:.2e} m)")
    print(f"worst: height {worst['h']:.2e} m, velocity {worst['v']:.2e} m/s, time {worst['t']:.2e} s")
    if errors:
        for e in errors:
            print("ERROR:", e, file=sys.stderr)
        return 1
    print("OFFLINE SOLVER CROSS-CHECK PASS (equations only; NOT the py-ballisticcalc acceptance run)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
